---
# This Kustomization waits for MetalLB HelmRelease to be ready before applying config
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/talos-cluster-1/metallb-config
  prune: true
  wait: true
  # Wait for MetalLB HelmRelease to install CRDs
  dependsOn:
    - name: infrastructure-controllers
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
