apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 30m
  chart:
    spec:
      chart: renovate
      version: '42.12.2'
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    renovate:
      config: |
        {}
    extraEnvFrom:
      - configMapRef:
          name: renovate-configmap
      - secretRef:
          name: renovate-pat
