apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m
  path: ./release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flamingo
  targetNamespace: argocd
