apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: argocd.local.t-a.dev
  dnsNames:
    - argocd.local.t-a.dev
