apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - argocd.yaml
  - ingress.yaml
patches:
  - patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
