apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

secretGenerator:
- name: sops-gpg
  namespace: flux-system
  files:
  - sops.asc=./sops.asc

patches:
- patch: |
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: sops-gpg
        secret:
          secretName: sops-gpg
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: sops-gpg
        mountPath: /home/flux/.sops
        readOnly: true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --sops-gpg
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --sops-gpg-disable-rekey
  target:
    kind: Deployment
    name: kustomize-controller
    namespace: flux-system
