apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

secretGenerator:
- name: sops-gpg
  namespace: flux-system
  files:
  - sops.asc=./sops.asc
