---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flamingo
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/flux-subsystem-argo/flamingo
  ref:
    tag: v2.6.6-fl.4-main-0d5eae51
